apiVersion: v1
kind: Pod
metadata:
 name: nginx-rediness
 labels:
  app: rediness1
spec:
 containers:
  - name: readiness1
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    readinessProbe:
     exec:
      command:
       - cat
       - /tmp/health
     initialDelaySeconds: 3
     periodSeconds: 3

