apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginxdeployment
 annotations:
  appname: paymentapp
  appversion: version2
  repoaddress: "https://github.com/myrepo"
  hash: "myhash"
  author: arya shahsvar
  releaseid: "1"
 labels:
  app: nginx-dp
spec:
 replicas: 3
 selector:
  matchLabels:
   app: payapp
 template:
  metadata:
   labels:
    app: payapp
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent

   nodeSelector:
    hdd: ssd


