apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: nginx
 name: nginx
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      env:
       - name: username
         valueFrom:
          secretKeyRef:
           name: usersecret
           key: username
       - name: password
         valueFrom:
          secretKeyRef:
           name: usersecret
           key: password
