apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 labels:
  app: dpsample
spec:
 replicas: 3
 selector:
  matchLabels:
   app: guestbook
   tier: frontend
 template:
  metadata:
   labels:
    app: guestbook
    tier: frontend
  spec:
   containers:
    - name: php-redis
      image: gcr.io/google-samples/gb-frontend:v4
      resources:
       requests:
        cpu: 100m
        memory: 100Mi
      env:
       - name: GET_HOST_FROM
         value: dns

