apiVersion: batch/v1
kind: Job
metadata:
 name: jobexample01
spec:
 template:
  metadata:
   name: jobexample01
  spec:
   containers:
    - name: job01
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sleep","20"]
  restartPolicy: OnFailure
