apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: nginxcfm1
 name: nginx
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   volumes:
    - name: nginx-config
      configMap:
       name: nginxconfig
   containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
       - name: nginx-config
         mountPath: /etc/nginx/conf.d
         readOnly: true


