apiVersion: v1
kind: Pod
metadata:
 name: resource-example2
 labels:
  app: stress-resource
spec:
 containers:
  - name: stress-example
    image: polinux/stress
    command: ["stress"]
    args: ["--vm","1","--vm-byte","300M","--vm-hand","1"]
    resources:
     requests:
      memory: "100Mi"
     limits:
      memory:  "200Mi"

