apiVersion: v1
kind: Pod
metadata:
 name: nginx-resource
 labels:
  app: resource1
spec:
 containers:
  - name: resource1
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
     requests:
      cpu: 50m
      memory: 500Mi
     limits:
      cpu: 200m
      memory: 1Gi

