apiVersion: v1
kind: Pod
metadata:
 name: webserver-liveness
 labels:
  app: liveness4
spec:
 containers:
  - name: tcp-liveness
    image: k8s.gcr.io/liveness
    args:
     - /server
    livenessProbe:
     tcpSocket:
      port: 8080
     initialDelaySeconds: 3
     periodSeconds: 3

