apiVersion: v1
kind: Pod
metadata:
 name: nginx-liveness
 labels:
  app: liveness2
spec:
 containers:
  - name: nginx-liveness
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
     exec:
      command:
       - cat
       - /var/run/nginx.pid
     initialDelaySeconds: 30

