apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
       - name: nginx-content
         persistentVolumeClaim:
          claimName: pvc1
       - name: nginx-config
         persistentVolumeClaim:
          claimName: pvc2
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
         - name: nginx-content
           mountPath: /usr/share/nginx/html
         - name: nginx-config
           mountPath: /etc/nginx/conf.d
