apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv1
spec:
 capacity:
  storage: 2Gi
 accessModes:
  - ReadWriteMany
 storageClassName: nfs
 mountOptions:
  - hard
  - nfsvers=4.1
 nfs:
  path: /var/nfs_share
  server: 192.168.47.131
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv2
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 storageClassName: nfs
 mountOptions:
  - hard
  - nfsvers=4.1
 nfs:
  path: /var/nfs_share
  server: 192.168.47.131
