apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc1
spec:
 storageClassName: nfs
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc2
spec:
 storageClassName: nfs
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 1Gi 
